/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg7_jairosierra;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jairo Sierra
 */
public class Principal extends javax.swing.JFrame {
adminArtista ap;
adminUsuario au;
adminTiempo HT = new adminTiempo(this.pg_t1);
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jmi_login.setVisible(false);
        jmi_logina.setVisible(false);
        jmi_parte.setVisible(false);
        jmi_parte2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearu = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_contra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jd_loginu = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pf_passpord = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jd_logina = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_user1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pf_passpord1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jd_creara = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_nombre1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_apellido1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jt_usuario1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jt_contra1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jd_fecha1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jd_artistamusica = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_canciones = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_seguidores = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_albumes = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        cb_artistas = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jd_crearAlbumes = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jt_nomal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jt_ano = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jd_crearcan = new javax.swing.JDialog();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jt_nombrecan = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jt_ano1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jt_duracion = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jd_can = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jt_nom = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jt_ano2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jt_duracion1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jd_musicausuario = new javax.swing.JDialog();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_canu = new javax.swing.JList<>();
        jButton13 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_playlist = new javax.swing.JList<>();
        jButton14 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_artistas = new javax.swing.JList<>();
        jButton15 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        cb_usuarios = new javax.swing.JComboBox<>();
        pg_t = new javax.swing.JProgressBar();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        pg_t1 = new javax.swing.JProgressBar();
        jLabel50 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        cb_canciones = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        cb_playlist = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jd_canu = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        cb_artista1 = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        cb_can1 = new javax.swing.JComboBox<>();
        jd_artu = new javax.swing.JDialog();
        jLabel40 = new javax.swing.JLabel();
        cb_artista2 = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        jd_playlist = new javax.swing.JDialog();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jt_playlist = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jt_genero = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jd_date1 = new com.toedter.calendar.JDateChooser();
        jLabel46 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jd_canplay = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        cb_play = new javax.swing.JComboBox<>();
        jButton20 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_usuario = new javax.swing.JMenu();
        jmi_crearu = new javax.swing.JMenuItem();
        jmi_login = new javax.swing.JMenuItem();
        jmi_parte = new javax.swing.JMenuItem();
        jm_artista = new javax.swing.JMenu();
        jmi_creara = new javax.swing.JMenuItem();
        jmi_logina = new javax.swing.JMenuItem();
        jmi_parte2 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Fecha de nacimiento");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearuLayout = new javax.swing.GroupLayout(jd_crearu.getContentPane());
        jd_crearu.getContentPane().setLayout(jd_crearuLayout);
        jd_crearuLayout.setHorizontalGroup(
            jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearuLayout.createSequentialGroup()
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearuLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(jd_crearuLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearuLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_nombre)
                                    .addComponent(jt_apellido)
                                    .addComponent(jt_usuario)
                                    .addComponent(jt_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearuLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jd_crearuLayout.setVerticalGroup(
            jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_crearuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Usuarios");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña");

        jButton2.setText("Ingresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginuLayout = new javax.swing.GroupLayout(jd_loginu.getContentPane());
        jd_loginu.getContentPane().setLayout(jd_loginuLayout);
        jd_loginuLayout.setHorizontalGroup(
            jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginuLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel8))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_loginuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGap(75, 75, 75)
                    .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pf_passpord, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(tf_user))
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        jd_loginuLayout.setVerticalGroup(
            jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginuLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
            .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_loginuLayout.createSequentialGroup()
                    .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_loginuLayout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(jLabel9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginuLayout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(34, 34, 34)
                    .addGroup(jd_loginuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(pf_passpord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(114, Short.MAX_VALUE)))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Artista");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Usuario");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Contraseña");

        jButton4.setText("Ingresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_loginaLayout = new javax.swing.GroupLayout(jd_logina.getContentPane());
        jd_logina.getContentPane().setLayout(jd_loginaLayout);
        jd_loginaLayout.setHorizontalGroup(
            jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginaLayout.createSequentialGroup()
                .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginaLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton4))
                    .addGroup(jd_loginaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)
                        .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_user1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(pf_passpord1)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jd_loginaLayout.setVerticalGroup(
            jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(45, 45, 45)
                .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_user1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jd_loginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(pf_passpord1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jButton4)
                .addGap(36, 36, 36))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Crear Artista");

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellido");

        jLabel13.setText("Usuario");

        jLabel14.setText("Contraseña");

        jLabel15.setText("Fecha de nacimiento");

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearaLayout = new javax.swing.GroupLayout(jd_creara.getContentPane());
        jd_creara.getContentPane().setLayout(jd_crearaLayout);
        jd_crearaLayout.setHorizontalGroup(
            jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearaLayout.createSequentialGroup()
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearaLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_nombre1)
                                    .addComponent(jt_apellido1)
                                    .addComponent(jt_usuario1)
                                    .addComponent(jt_contra1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearaLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jd_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearaLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jd_crearaLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jButton3)))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jd_crearaLayout.setVerticalGroup(
            jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jt_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jt_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_contra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_crearaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jd_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Artistas");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Seguidores");

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Albumes");

        jl_canciones.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_canciones);

        jButton6.setText("Crear Album");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Sencillos");

        jl_seguidores.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_seguidores);

        jl_albumes.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_albumes);

        jButton7.setText("Crear Sencillo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        cb_artistas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_artistasItemStateChanged(evt);
            }
        });

        jButton12.setText("Actualizar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_artistamusicaLayout = new javax.swing.GroupLayout(jd_artistamusica.getContentPane());
        jd_artistamusica.getContentPane().setLayout(jd_artistamusicaLayout);
        jd_artistamusicaLayout.setHorizontalGroup(
            jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(58, 58, 58))
                    .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(162, 162, 162)
                        .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(47, 47, 47))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_artistamusicaLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(cb_artistas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(526, Short.MAX_VALUE)))
        );
        jd_artistamusicaLayout.setVerticalGroup(
            jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                        .addComponent(cb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addGap(135, 135, 135))
            .addGroup(jd_artistamusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_artistamusicaLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel23.setText("Crear Albumes");

        jLabel24.setText("Nombre");

        jLabel25.setText("Año");

        jLabel26.setText("Canciones");

        jButton8.setText("Crear Canciones");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Crear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearAlbumesLayout = new javax.swing.GroupLayout(jd_crearAlbumes.getContentPane());
        jd_crearAlbumes.getContentPane().setLayout(jd_crearAlbumesLayout);
        jd_crearAlbumesLayout.setHorizontalGroup(
            jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearAlbumesLayout.createSequentialGroup()
                .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearAlbumesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addGap(38, 38, 38)
                        .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nomal)
                            .addComponent(jt_ano, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jButton8)))
                    .addGroup(jd_crearAlbumesLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton9))
                    .addGroup(jd_crearAlbumesLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel23)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jd_crearAlbumesLayout.setVerticalGroup(
            jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearAlbumesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(24, 24, 24)
                .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jt_nomal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jd_crearAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(43, 43, 43))
        );

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Crear Sencillos");

        jLabel28.setText("Nombre");

        jLabel29.setText("Año");

        jLabel30.setText("Duracion (Segundos) ");

        jButton10.setText("Crear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearcanLayout = new javax.swing.GroupLayout(jd_crearcan.getContentPane());
        jd_crearcan.getContentPane().setLayout(jd_crearcanLayout);
        jd_crearcanLayout.setHorizontalGroup(
            jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcanLayout.createSequentialGroup()
                .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearcanLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel27))
                    .addGroup(jd_crearcanLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(31, 31, 31)
                        .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_nombrecan)
                                .addComponent(jt_ano1)
                                .addComponent(jt_duracion, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jd_crearcanLayout.setVerticalGroup(
            jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearcanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addGap(36, 36, 36)
                .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jt_nombrecan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jt_ano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jd_crearcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton10)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Crear Canciones");

        jLabel32.setText("Nombre");

        jLabel33.setText("Año");

        jLabel34.setText("Duracion (Segundos) ");

        jButton11.setText("Crear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_canLayout = new javax.swing.GroupLayout(jd_can.getContentPane());
        jd_can.getContentPane().setLayout(jd_canLayout);
        jd_canLayout.setHorizontalGroup(
            jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canLayout.createSequentialGroup()
                .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_canLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel31))
                    .addGroup(jd_canLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(31, 31, 31)
                        .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_nom)
                                .addComponent(jt_ano2)
                                .addComponent(jt_duracion1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jd_canLayout.setVerticalGroup(
            jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel31)
                .addGap(36, 36, 36)
                .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jt_ano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jd_canLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jt_duracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Canciones");

        jl_canu.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_canu);

        jButton13.setText("Agregar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Playlist");

        jl_playlist.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_playlist);

        jButton14.setText("Agregar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel38.setText("Artistas");

        jl_artistas.setModel(new DefaultListModel());
        jScrollPane9.setViewportView(jl_artistas);

        jButton15.setText("Agregar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel35.setText("Usuarios");

        pg_t.setForeground(new java.awt.Color(255, 0, 0));
        pg_t.setMaximum(1440);
        pg_t.setToolTipText("");
        pg_t.setString(Integer.toString(pg_t.getValue())+" Minutos");
        pg_t.setStringPainted(true);

        jLabel48.setText("Tiempo Transcurrido Playlist");

        jLabel49.setText("Tiempo transcurrido Cancion ");

        pg_t1.setForeground(new java.awt.Color(255, 0, 0));
        pg_t1.setMaximum(1440);
        pg_t1.setToolTipText("");
        pg_t1.setString(Integer.toString(pg_t.getValue())+" Minutos");
        pg_t1.setStringPainted(true);

        jLabel50.setText("Canciones");

        jButton21.setText("Reproducir");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel51.setText("Playlist");

        jButton22.setText("Reproducir");

        jLabel52.setText("Canciones Reproduciendose");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Año", "Artista", "Duracion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout jd_musicausuarioLayout = new javax.swing.GroupLayout(jd_musicausuario.getContentPane());
        jd_musicausuario.getContentPane().setLayout(jd_musicausuarioLayout);
        jd_musicausuarioLayout.setHorizontalGroup(
            jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_musicausuarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addGap(121, 121, 121)
                .addComponent(jLabel38)
                .addGap(187, 187, 187)
                .addComponent(jLabel37)
                .addGap(48, 48, 48))
            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton15)
                        .addGap(130, 130, 130)
                        .addComponent(jButton13)
                        .addGap(32, 32, 32))
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(cb_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel51)
                        .addGap(18, 18, 18)
                        .addComponent(cb_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22)
                .addGap(64, 64, 64))
            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pg_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(pg_t, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_musicausuarioLayout.setVerticalGroup(
            jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel38))
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel37)
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton14))
                            .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton13)
                                    .addComponent(jButton15))))
                        .addGap(73, 73, 73)
                        .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(cb_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51))
                        .addGap(26, 26, 26)
                        .addComponent(jButton21))
                    .addGroup(jd_musicausuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton22)))
                .addGap(65, 65, 65)
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(pg_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jd_musicausuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(pg_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jLabel39.setText("Artista");

        cb_artista1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_artista1ItemStateChanged(evt);
            }
        });

        jButton16.setText("Agregar ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel41.setText("Canciones");

        cb_can1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_can1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_canuLayout = new javax.swing.GroupLayout(jd_canu.getContentPane());
        jd_canu.getContentPane().setLayout(jd_canuLayout);
        jd_canuLayout.setHorizontalGroup(
            jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canuLayout.createSequentialGroup()
                .addGroup(jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_canuLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addGroup(jd_canuLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(62, 62, 62)
                                .addGroup(jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_artista1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_can1, 0, 134, Short.MAX_VALUE)))))
                    .addGroup(jd_canuLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton16)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_canuLayout.setVerticalGroup(
            jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(cb_artista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jd_canuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(cb_can1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(jButton16)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel40.setText("Artistas");

        jButton17.setText("Seguir");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_artuLayout = new javax.swing.GroupLayout(jd_artu.getContentPane());
        jd_artu.getContentPane().setLayout(jd_artuLayout);
        jd_artuLayout.setHorizontalGroup(
            jd_artuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artuLayout.createSequentialGroup()
                .addGroup(jd_artuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_artuLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel40)
                        .addGap(61, 61, 61)
                        .addComponent(cb_artista2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_artuLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton17)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jd_artuLayout.setVerticalGroup(
            jd_artuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_artuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jd_artuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cb_artista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jButton17)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("PlayList");

        jLabel43.setText("Nombre");

        jLabel44.setText("Genero");

        jLabel45.setText("fecha");

        jLabel46.setText("Canciones");

        jButton18.setText("Agregar Canciones");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Crear");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_playlistLayout = new javax.swing.GroupLayout(jd_playlist.getContentPane());
        jd_playlist.getContentPane().setLayout(jd_playlistLayout);
        jd_playlistLayout.setHorizontalGroup(
            jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playlistLayout.createSequentialGroup()
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_playlistLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel42))
                    .addGroup(jd_playlistLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addGap(48, 48, 48)
                        .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18)
                            .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_playlist)
                                .addComponent(jt_genero)
                                .addComponent(jd_date1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                    .addGroup(jd_playlistLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton19)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jd_playlistLayout.setVerticalGroup(
            jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playlistLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel42)
                .addGap(43, 43, 43)
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jd_date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jButton18))
                .addGap(64, 64, 64)
                .addComponent(jButton19)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel47.setText("Canciones");

        jButton20.setText("Agregar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_canplayLayout = new javax.swing.GroupLayout(jd_canplay.getContentPane());
        jd_canplay.getContentPane().setLayout(jd_canplayLayout);
        jd_canplayLayout.setHorizontalGroup(
            jd_canplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canplayLayout.createSequentialGroup()
                .addGroup(jd_canplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_canplayLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(cb_play, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_canplayLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton20)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jd_canplayLayout.setVerticalGroup(
            jd_canplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_canplayLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jd_canplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(cb_play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButton20)
                .addGap(97, 97, 97))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_usuario.setText("Usuarios");

        jmi_crearu.setText("Crear Usuario");
        jmi_crearu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearuActionPerformed(evt);
            }
        });
        jm_usuario.add(jmi_crearu);

        jmi_login.setText("Login");
        jmi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_loginActionPerformed(evt);
            }
        });
        jm_usuario.add(jmi_login);

        jmi_parte.setText("Parte Musical");
        jmi_parte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_parteActionPerformed(evt);
            }
        });
        jm_usuario.add(jmi_parte);

        jMenuBar1.add(jm_usuario);

        jm_artista.setText("Artistas");

        jmi_creara.setText("Crear Artista");
        jmi_creara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearaActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_creara);

        jmi_logina.setText("Login");
        jmi_logina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_loginaActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_logina);

        jmi_parte2.setText("Parte Musical");
        jmi_parte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_parte2ActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_parte2);

        jMenuBar1.add(jm_artista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_nombre.getText();
        String apellido = jt_apellido.getText();
        String usuario = jt_usuario.getText();
        String contrasena = jt_contra.getText();
        Date fecha = jd_fecha.getDate();
        Usuario x = new Usuario(nombre, apellido, usuario, contrasena, fecha);
        lista.add(x);
        au = new adminUsuario("./Archivos Binarios/usuarios.cbm");
        au.cargarArchivo();
        au.setUsuario(x);
        au.escribirArchivo();
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(au.getListaUsuarios().toArray());
            cb_usuarios.setModel(modelo1);
        JOptionPane.showMessageDialog(jd_crearu, "Agregado exitosamente");
        jt_nombre.setText("");
        jt_apellido.setText("");
        jt_usuario.setText("");
        jt_contra.setText("");
        jd_fecha.setDate(new Date());
        jd_loginu.setModal(true);
        jmi_login.setVisible(true);
        jd_crearu.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < lista.size(); i++) {
            if (tf_user.getText().equals(((Usuario) lista.get(i)).getUsuario()) && pf_passpord.getText().equals(((Usuario) lista.get(i)).getContrasena())) {
                jmi_parte.setVisible(true);
                tf_user.setText("");
                pf_passpord.setText("");
                jd_loginu.dispose();
            } else {
                JOptionPane.showMessageDialog(jd_logina, "Datos Incorrectos");
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jmi_crearuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearuActionPerformed
        // TODO add your handling code here:
        jd_crearu.setModal(true);
        jd_crearu.pack();
        jd_crearu.setLocationRelativeTo(this);
        jd_crearu.setVisible(true);
    }//GEN-LAST:event_jmi_crearuActionPerformed

    private void jmi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_loginActionPerformed
        // TODO add your handling code here:
        jd_loginu.setModal(true);
        jd_loginu.pack();
        jd_loginu.setLocationRelativeTo(this);
        jd_loginu.setVisible(true);
    }//GEN-LAST:event_jmi_loginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_nombre1.getText();
        String apellido = jt_apellido1.getText();
        String usuario = jt_usuario1.getText();
        String contrasena = jt_contra1.getText();
        Date fecha = jd_fecha1.getDate();
        Artista x = new Artista(nombre, apellido, usuario, contrasena, fecha);
        lista.add(x);
        ap = new adminArtista("./Archivos Binarios/artistas.cbm");
        ap.cargarArchivo();
        ap.setArtista(x);
        ap.escribirArchivo();
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(ap.getListaArtistas().toArray());
            cb_artistas.setModel(modelo1);
            cb_artista1.setModel(modelo1);
            cb_artista2.setModel(modelo1);
        JOptionPane.showMessageDialog(jd_creara, "Agregado exitosamente");
        jt_nombre1.setText("");
        jt_apellido1.setText("");
        jt_usuario1.setText("");
        jt_contra1.setText("");
        jd_fecha1.setDate(new Date());
        jmi_logina.setVisible(true);
        jd_creara.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jmi_crearaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearaActionPerformed
        // TODO add your handling code here:
        jd_creara.setModal(true);
        jd_creara.pack();
        jd_creara.setLocationRelativeTo(this);
        jd_creara.setVisible(true);
    }//GEN-LAST:event_jmi_crearaActionPerformed

    private void jmi_loginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_loginaActionPerformed
        // TODO add your handling code here:
        jd_logina.setModal(true);
        jd_logina.pack();
        jd_logina.setLocationRelativeTo(this);
        jd_logina.setVisible(true);
    }//GEN-LAST:event_jmi_loginaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < lista.size(); i++) {
            if (tf_user1.getText().equals(((Artista) lista.get(i)).getUsuario()) && pf_passpord1.getText().equals(((Artista) lista.get(i)).getContrasena())) {
                jmi_parte2.setVisible(true);
                tf_user1.setText("");
                pf_passpord1.setText("");
                jd_logina.dispose();
            } else {
                JOptionPane.showMessageDialog(jd_logina, "Datos Incorrectos");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jmi_parteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_parteActionPerformed
        // TODO add your handling code here:
        jd_musicausuario.setModal(true);
        jd_musicausuario.pack();
        jd_musicausuario.setLocationRelativeTo(this);
        jd_musicausuario.setVisible(true);
    }//GEN-LAST:event_jmi_parteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(cb_artistas.getSelectedIndex()>=0){
        DefaultListModel modelo = (DefaultListModel) jl_seguidores.getModel();
            modelo.addElement(ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getSeguidores());
            jl_seguidores.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un artista");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jd_crearAlbumes.setModal(true);
        jd_crearAlbumes.pack();
        jd_crearAlbumes.setLocationRelativeTo(this);
        jd_crearAlbumes.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       jd_can.setModal(true);
        jd_can.pack();
        jd_can.setLocationRelativeTo(this);
        jd_can.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_nom.getText();
    String ano = jt_ano2.getText();
    String artista = ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getNombre();
    String duracion = jt_duracion1.getText();
    Cancion x = new Cancion(nombre,ano,artista,duracion);
    lis.add(x);
    JOptionPane.showMessageDialog(this, "Agregada exitosamente");
    jt_nom.setText("");
    jt_ano2.setText("");
    jt_duracion1.setText("");
    jd_can.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_nombrecan.getText();
    String ano = jt_ano1.getText();
    String artista = ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getNombre();
    String duracion = jt_duracion.getText();
    Cancion x = new Cancion(nombre,ano,artista,duracion);
    ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getCanciones().add(x);
    JOptionPane.showMessageDialog(this, "Agregada exitosamente");
    jt_nombrecan.setText("");
    jt_ano1.setText("");
    jt_duracion.setText("");
    jd_crearcan.dispose();
    if(cb_artistas.getSelectedIndex()>=0){
        DefaultListModel modelo = (DefaultListModel) jl_canciones.getModel();
            modelo.addElement(ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getCanciones());
            jl_canciones.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un artista");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_nomal.getText();
        String ano = jt_ano.getText();
        String artista = ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getNombre();
        Album x = new Album(nombre,ano,artista);
        x.setCanciones(lis);
        ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getAlbumes().add(x);
        JOptionPane.showMessageDialog(this, "Agregada exitosamente");
        jt_nomal.setText("");
        jt_ano.setText("");
        jd_crearAlbumes.dispose();
        if(cb_artistas.getSelectedIndex()>=0){
        DefaultListModel modelo = (DefaultListModel) jl_albumes.getModel();
            modelo.addElement(ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getAlbumes());
            jl_albumes.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un artista");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jd_crearcan.setModal(true);
        jd_crearcan.pack();
        jd_crearcan.setLocationRelativeTo(this);
        jd_crearcan.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jmi_parte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_parte2ActionPerformed
        // TODO add your handling code here:
        jd_artistamusica.setModal(true);
        jd_artistamusica.pack();
        jd_artistamusica.setLocationRelativeTo(this);
        jd_artistamusica.setVisible(true);
    }//GEN-LAST:event_jmi_parte2ActionPerformed

    private void cb_artistasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_artistasItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_artistasItemStateChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(cb_artistas.getSelectedIndex()>=0){
        DefaultListModel modelo = (DefaultListModel) jl_albumes.getModel();
        modelo.clear();
            modelo.addElement(ap.getListaArtistas().get(cb_artistas.getSelectedIndex()).getAlbumes());
            jl_albumes.setModel(modelo);
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un artista");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jd_playlist.setModal(true);
        jd_playlist.pack();
        jd_playlist.setLocationRelativeTo(this);
        jd_playlist.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         jd_canu.setModal(true);
        jd_canu.pack();
        jd_canu.setLocationRelativeTo(this);
        jd_canu.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void cb_artista1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_artista1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 1) {
            DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(ap.getListaArtistas().toArray());
            modelo1.addElement(ap.getListaArtistas().get(cb_artista1.getSelectedIndex()).getCanciones());
            cb_can1.setModel(modelo1);
        }
    }//GEN-LAST:event_cb_artista1ItemStateChanged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Cancion x = ap.getListaArtistas().get(cb_artista1.getSelectedIndex()).getCanciones().get(cb_can1.getSelectedIndex());
        au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getCanciones().add(x);
        JOptionPane.showMessageDialog(this, "Agregada Exitosamente");
        jd_canu.dispose();
        DefaultListModel modelo = (DefaultListModel) jl_canu.getModel();
        modelo.addElement(au.getListaUsuarios().get((cb_usuarios.getSelectedIndex())).getCanciones());
        jl_canu.setModel(modelo);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void cb_can1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_can1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_can1ItemStateChanged

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jd_artu.setModal(true);
        jd_artu.pack();
        jd_artu.setLocationRelativeTo(this);
        jd_artu.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Artista x = ap.getListaArtistas().get(cb_artista2.getSelectedIndex());
        au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getArtistas().add(x);
        ap.getListaArtistas().get(cb_artista2.getSelectedIndex()).getSeguidores().add(au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()));
        JOptionPane.showMessageDialog(this, "Se siguio correctamente");
        jd_artu.dispose();
        DefaultListModel modelo = (DefaultListModel) jl_artistas.getModel();
        modelo.addElement(au.getListaUsuarios().get((cb_usuarios.getSelectedIndex())).getArtistas());
        jl_artistas.setModel(modelo);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jd_canplay.setModal(true);
        jd_canplay.pack();
        jd_canplay.setLocationRelativeTo(this);
        jd_canplay.setVisible(true);
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(au.getListaUsuarios().toArray());
        modelo1.addElement(au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getCanciones());
            cb_play.setModel(modelo1);
            cb_canciones.setModel(modelo1);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        Cancion x = au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getCanciones().get(cb_play.getSelectedIndex());
        x.getDuracion();
        duracion+=Double.parseDouble(x.getDuracion());
        lis2.add(x);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        String nombre = jt_playlist.getText();
    String genero=jt_genero.getText();
   Date fecha = jd_fecha1.getDate();
   Playlist x = new Playlist(nombre,genero,fecha,duracion);
   x.setCanciones(lis2);
   au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getLista().add(x);
   JOptionPane.showMessageDialog(this, "Se creo exitosamente");
   jt_playlist.setText("");
   jt_genero.setText("");
   jd_fecha1.setDate(new Date());
   DefaultListModel modelo = (DefaultListModel) jl_playlist.getModel();
        modelo.addElement(au.getListaUsuarios().get((cb_usuarios.getSelectedIndex())).getLista());
        jl_playlist.setModel(modelo);
        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(au.getListaUsuarios().toArray());
        modelo1.addElement(au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getLista());
            cb_playlist.setModel(modelo1);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
////        Object [] newrow={
////            ((Cancion)au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getCanciones()).
////        }
        double duracion=0;
        duracion = Double.parseDouble(au.getListaUsuarios().get(cb_usuarios.getSelectedIndex()).getCanciones().get(cb_canciones.getSelectedIndex()).getDuracion());
        int c = (int)duracion*1000;
        
        try { //por si ya esta iniciado
//            HT = new adminTiempo(pg_t1.set);
                HT.start();
            }            
         catch (Exception e) {
        }        
        HT.setAvanzar(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_artista1;
    private javax.swing.JComboBox<String> cb_artista2;
    private javax.swing.JComboBox<String> cb_artistas;
    private javax.swing.JComboBox<String> cb_can1;
    private javax.swing.JComboBox<String> cb_canciones;
    private javax.swing.JComboBox<String> cb_play;
    private javax.swing.JComboBox<String> cb_playlist;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDialog jd_artistamusica;
    private javax.swing.JDialog jd_artu;
    private javax.swing.JDialog jd_can;
    private javax.swing.JDialog jd_canplay;
    private javax.swing.JDialog jd_canu;
    private javax.swing.JDialog jd_crearAlbumes;
    private javax.swing.JDialog jd_creara;
    private javax.swing.JDialog jd_crearcan;
    private javax.swing.JDialog jd_crearu;
    private com.toedter.calendar.JDateChooser jd_date1;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private com.toedter.calendar.JDateChooser jd_fecha1;
    private javax.swing.JDialog jd_logina;
    private javax.swing.JDialog jd_loginu;
    private javax.swing.JDialog jd_musicausuario;
    private javax.swing.JDialog jd_playlist;
    private javax.swing.JList<String> jl_albumes;
    private javax.swing.JList<String> jl_artistas;
    private javax.swing.JList<String> jl_canciones;
    private javax.swing.JList<String> jl_canu;
    private javax.swing.JList<String> jl_playlist;
    private javax.swing.JList<String> jl_seguidores;
    private javax.swing.JMenu jm_artista;
    private javax.swing.JMenu jm_usuario;
    private javax.swing.JMenuItem jmi_creara;
    private javax.swing.JMenuItem jmi_crearu;
    private javax.swing.JMenuItem jmi_login;
    private javax.swing.JMenuItem jmi_logina;
    private javax.swing.JMenuItem jmi_parte;
    private javax.swing.JMenuItem jmi_parte2;
    private javax.swing.JTextField jt_ano;
    private javax.swing.JTextField jt_ano1;
    private javax.swing.JTextField jt_ano2;
    private javax.swing.JTextField jt_apellido;
    private javax.swing.JTextField jt_apellido1;
    private javax.swing.JTextField jt_contra;
    private javax.swing.JTextField jt_contra1;
    private javax.swing.JTextField jt_duracion;
    private javax.swing.JTextField jt_duracion1;
    private javax.swing.JTextField jt_genero;
    private javax.swing.JTextField jt_nom;
    private javax.swing.JTextField jt_nomal;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombre1;
    private javax.swing.JTextField jt_nombrecan;
    private javax.swing.JTextField jt_playlist;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JTextField jt_usuario1;
    private javax.swing.JPasswordField pf_passpord;
    private javax.swing.JPasswordField pf_passpord1;
    public javax.swing.JProgressBar pg_t;
    public javax.swing.JProgressBar pg_t1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_user1;
    // End of variables declaration//GEN-END:variables
ArrayList<Persona> lista = new ArrayList();
ArrayList<Cancion> lis = new ArrayList();
ArrayList<Cancion> lis2 = new ArrayList();
double duracion=0;
}
